use_default_settings:
  engines:
    keep_only:
      - wikipedia
      - wikidata
      - duckduckgo
      - mojeek
      - stract
      - bing
      - brave

general:
  instance_name: "AgentSearch"

search:
  formats:
    - html
    - json

outgoing:
  request_timeout: 8.0
  max_request_timeout: 8.0
  retries: 2

server:
  limiter: false
  image_proxy: true

ui:
  static_use_hash: true
