use_default_settings:
  engines:
    keep_only:
      - wikipedia
      - wikidata
      - duckduckgo
      - mojeek
      - bing
      - brave

general:
  instance_name: "AgentSearch"

search:
  formats:
    - html
    - json

outgoing:
  request_timeout: 8.0
  max_request_timeout: 10.0
  retries: 2

engines:
  - name: google-api
    engine: google_api
    shortcut: goapi
    categories: general
    disabled: false
    weight: 10
    timeout: 8.0
    no_result_for_http_status: [400, 401, 403, 429]
  - name: wikipedia
    disabled: false
  - name: wikidata
    disabled: false
  - name: duckduckgo
    disabled: false
    timeout: 10.0
  - name: mojeek
    disabled: false
  - name: bing
    disabled: false
  - name: brave
    disabled: false

server:
  limiter: false
  image_proxy: true

ui:
  static_use_hash: true
